### ISSUE TITLE
Use a config var so user does not have to hunt thru the tasks to setup.

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#11]
To make configuration easier, I suggest having a config var at the top which would contain all the necessary configurations for initial setup so the user does  not need to hunt thru the tasks to setup paths and domains.

This pretty much be required if #10 is implemented.

Example from another project:
https://github.com/archetyped/simple-lightbox/blob/master/Gruntfile.js#L11

**Comment by grappler** [comment]
I did something similar here. https://github.com/wpzoo/grunt

**Comment by shazahm1** [comment]
I'm a new to Node/Grunt but @grappler shouldn't configuration options be within the `config` object in package.json to be compliant?

file:///C:/Program%20Files/nodejs/node_modules/npm/html/doc/files/package.json.html#config

I just noticed that is a local file, you can bring it via this command: `npm help json`

Any ways... It seems that would be the way to go that way the Gruntfile does not need to be edited at all and it'll simplify initial setup

**Comment by fxbenard** [comment]
You always have something to setup first - No need to mess with the json config file

**Comment by shazahm1** [comment]
Alrighty, thanks for the consideration.
