### ISSUE TITLE
Missing PHP CLI in Requirements

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#13]
I know this is actually a requirement of grunt-wp-i18n... but it was not immediately obvious to me why make would fail until I stepped thru the code. Having it listed as a requirement... I would have made sure to install it to begin with.

**Comment by fxbenard** [comment]
where to you need php cli?

**Comment by shazahm1** [comment]
PHP CLI is required by grunt-wp-i18n:

https://github.com/cedaro/grunt-wp-i18n

**Comment by fxbenard** [comment]
Closed by https://github.com/WP-Translations/grunt-transifex-wordpress/commit/43d8aaecd1013efd83bc4535bc6b3a2e885aa7df
