### ISSUE TITLE
Missing New Line?

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#14]
Is this messing a new line `\n`?

**Comment by shazahm1** [comment]
Actually they do not seem to be required at all as wp-i18n will add them as needed.

**Comment by fxbenard** [comment]
Exactly - I close

**Comment by shazahm1** [comment]
Right... but this project includes the newlines and they're not needed.
- https://github.com/WP-Translations/grunt-transifex-wordpress/blob/master/Gruntfile.js#L26
- https://github.com/WP-Translations/grunt-transifex-wordpress/blob/master/Gruntfile.js#L27

**Comment by fxbenard** [comment]
closed by https://github.com/WP-Translations/grunt-transifex-wordpress/commit/c2edd5b6a056167051ebdc1ae6e9a0c5a00c32a3

**Comment by fxbenard** [comment]
good catch thanks
