### ISSUE TITLE
makepot, Incorrect POT Headers.

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#15]
Per the docs: https://www.gnu.org/software/gettext/manual/html_node/Header-Entry.html

The Last-Translator header is to be set to:
https://github.com/WP-Translations/grunt-transifex-wordpress/blob/master/Gruntfile.js#L26

> name and email address (without double quotes).

The Language-Team header is to be set to:
https://github.com/WP-Translations/grunt-transifex-wordpress/blob/master/Gruntfile.js#L27

> name of the language, and the email address or homepage URL

**Comment by fxbenard** [comment]
That's the way to setup on grunt wp-i18n
See here https://github.com/cedaro/grunt-wp-i18n/blob/develop/docs/examples/custom-working-directory.md
Check the pot created everything is working fine

**Comment by shazahm1** [comment]
I did check the POT before posting. According to the man for gettext the Last-Translator should be name <email> and currently this is setup as name (url). Language-Team team is actually fine since it can be name <email> or name (url)

**Comment by fxbenard** [comment]
Thanks, corrected via https://github.com/WP-Translations/grunt-transifex-wordpress/commit/3b5c19cf6258809562b7f588c8b11047250c8594
