### ISSUE TITLE
Global task

### ISSUE THREAD

**Issue by michaelbeil** [WP-Translations/grunt-transifex-wordpress#16]
Is there a new task name to run `grunt tx-pull`, `grunt go-pot`, `grunt tx-push` in one command or is there a recommended order?

**Comment by fxbenard** [comment]
For now on no new global task, but it's doable! Even if I think tx-push and tx-pull should remain 2 separated tasks
Recommended order :
- go-pot + tx-push
- tx-pull

**Comment by michaelbeil** [comment]
Thanks @fxbenard!
