### ISSUE TITLE
Correct settings for _n() keywork in the grunt checktextdomain command.

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#17]
In light of this:
https://github.com/easydigitaldownloads/Easy-Digital-Downloads/commit/ee0b4ebc01fbf2b57236103a09e45043f9ea60e4#commitcomment-10480942

Will this be updated?

**Comment by fxbenard** [comment]
Yes done via 1ce7554ae07b115aad737b7ae8f44142aab50ef7
Needed to be pushed, thanks

**Comment by shazahm1** [comment]
No problem... and thank you! this tool has been awesome! Makes it incredibly easy to manage translations. In fact Grunt has been awesome to work with. I've been adding a lot more build tasks. You can see in my [Gruntfile.js](https://github.com/Connections-Business-Directory/Connections/blob/develop/Gruntfile.js).

**Comment by fxbenard** [comment]
Really glad you found my tasks useful. I might borrow you some ideas for the variables implementation.
Lovely to see what you have done with your grunt file
