### ISSUE TITLE
makepot excludes

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#18]
Question... shouldn't the node_modules be excluded in the makepot task?

**Comment by fxbenard** [comment]
Makepot only check for php files. So i guess it's ok like that

**Comment by shazahm1** [comment]
The reason I happened to notice it is because grunt-wp-i18n, which is a dependency, contains PHP files in its vendor folder but these might already be excluded as a default, I dunno for sure.

**Comment by fxbenard** [comment]
I guess it is, I never had any pot files with node_modules content in it. @bradyvercher Can you confirm that please

**Comment by shazahm1** [comment]
My guess it is being excluded automagically... but what I was really thinking what if there are other node_modules with PHP files... what would happen?

**Comment by bradyvercher** [comment]
Yep, the `node_modules` directory is excluded by default: https://github.com/cedaro/grunt-wp-i18n/blob/3dce54d22f127969d399160204ff482ad28a34df/tasks/makepot.js#L92-L93

**Comment by fxbenard** [comment]
@bradyvercher Thanks for the confirmation and your amazing tool
@shazahm1 I let you close this - We're safe to go
