### ISSUE TITLE
grunt go-pot + tx-push

### ISSUE THREAD

**Issue by michaelbeil** [WP-Translations/grunt-transifex-wordpress#19]
what would the command be to combine these?

`grunt go-pot tx-push`

Appears to be this.

**Comment by michaelbeil** [comment]
Ok, so `grunt go-pot tx-push tx-pull` seems to cover it. 

:+1:

**Comment by fxbenard** [comment]
@michaelbeil Yes it was the idea ;)
Now you can create a new task, grouping everything together. 
I separate the go-pot cause sometimes you have fix to do before pushing to TX (checktextdomain).
Tell me if you want it anyway

**Comment by michaelbeil** [comment]
This makes perfect sense @fxbenard. Appreciate the progress being made.
