### ISSUE TITLE
Build path not being excluded?

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#5]
Honestly, not sure if this is a bug since I am not familiar with Node/Grunt an such, just learning...

That said, it appears that the build path is not being excluded:
https://github.com/WP-Translations/grunt-transifex-wordpress/blob/master/Gruntfile.js#L78

**Comment by fxbenard** [comment]
The PR was holding on my local ;) Thanks
closed with https://github.com/WP-Translations/grunt-transifex-wordpress/commit/da7fe5dcd873033df91a4f7e6547abdc6224a809
