### ISSUE TITLE
Transifex Client Setup Documentation

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#6]
In the setup there is no mention of the client setup for the .transifexrc file. It would probably be good to mention it. It took me about 5 minutes to track down the info.

http://docs.transifex.com/developer/client/config#transifexrc

A better solution is to have the tash ask for user login and password and not store the details in clear text but that might be a limitation to the tx client.

**Comment by shazahm1** [comment]
Maybe instead of using the tx client... use this instead:
https://www.npmjs.com/package/grunt-transifex-resjson

User login/pass are not need to be save in a clear text file.

I'd give it a go an do a pull request ... but I'm very new to Node/Grunt so this would be outside of what I can do at the moment.

**Comment by fxbenard** [comment]
Close for now with #da7fe5dcd873033df91a4f7e6547abdc6224a809

**Comment by fxbenard** [comment]
Close https://github.com/WP-Translations/grunt-transifex-wordpress/commit/e08e33a95481eccc765f006ad81a1e9316c9adff

Your PR most welcome with the other grunt task - Use another branch please
