### ISSUE TITLE
checktextdomain text_domain Comment

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#7]
There probably should be a comment to change the text domina from foo to the plugin/theme text domain.

**Comment by fxbenard** [comment]
On my todo list - Thanks

**Comment by fxbenard** [comment]
Should be unnecessary when #10 will be implemented

**Comment by fxbenard** [comment]
Closed with e1f26f1575ea694d14c050013d90eade41d4b5e2 and c9e850b5fb5b6c782431266fbf13492d70b30690
