### ISSUE TITLE
grunt Command Documentation

### ISSUE THREAD

**Issue by shazahm1** [WP-Translations/grunt-transifex-wordpress#9]
Under the How it works sections, for Windows users, there should be a note that since Node.js uses the cms shell the the grunt tasks provided by this need to be run from the cmd shell. This is important because if run from PowerShell the task will stall at `Running "potomo:dist" (potomo) task`. When run from the cmd shell the tasks will complete normally.

**Comment by fxbenard** [comment]
I'm not using powershell but the simple cmd.exe indeed. I never add this issue before. Can we maybe create an issue to the potomo grunt task as it's more an issue from this task?

**Comment by shazahm1** [comment]
I have no clue this is possible...

I do know Node can report which OS it is running on... I wonder if it knows from which shell it is running in. If it is possible, maybe check for for the shell and if it finds powershell, gracefully exit with an notice.

**Comment by fxbenard** [comment]
https://github.com/axisnodejs/grunt-potomo I'm not in charge of potomo I'm just using the tasks.

I have no idea how to check the shell in use. the task should be working straight out of the box

@shivapoudel can't you have a look, thanks

**Comment by shivapoudel** [comment]
Checked in PowerShell and works great what's the bug. @shazahm1 let us know if its really a 'bug' and please add the screenshot xD

If you still suffer then it's shelljs bug:
https://github.com/arturadib/shelljs/issues/17

**Comment by shazahm1** [comment]
@shivapoudel 

Here's a screen capture... does not show much, the task simply "stalls" I have to about it.

![2015-03-16_13-52-32](https://cloud.githubusercontent.com/assets/1185008/6672604/01a54582-cbe4-11e4-8dd3-9cb380cb12f1.png)

I tried adding the async flag to the shell command as mentioned in arturadib/shelljs#17 but that just causes it to fail ending with this error message:
`'Failed to Compile "*.po" files into binary "*.mo" files with "msgfmt".'`

**Comment by shivapoudel** [comment]
Oh, you got the error `'Failed to Compile "*.po" files into binary "*.mo" files with "msgfmt".'` ;)

This means your shell is not executing the `msgfmt` command, Install the GetText in your system PATH
https://github.com/axisthemes/grunt-potomo#requirements

**Comment by shazahm1** [comment]
Yep, I already have that in my path. Works fine from cmd.just not powershell (for me). Here's a screenshot showing the version from the powershell prompt, so powershell can run it:

![2015-03-16_14-29-31](https://cloud.githubusercontent.com/assets/1185008/6673408/27c754f8-cbe9-11e4-8b44-f148d51b7486.png)

**Comment by shivapoudel** [comment]
@shazahm1 So this is a shelljs bug and sorry to say but have a look to below snippet, there is the use of `shell.exec( 'some command' )` which cause the stall in Windows powershell.
https://github.com/axisthemes/grunt-potomo/blob/master/tasks/potomo.js#L53-L60

Till this bug https://github.com/arturadib/shelljs/issues/17 is resolved, I am not sure how to fix it up. If you have any idea then submit the PR xD

**Comment by shivapoudel** [comment]
@shazahm1 seems like issue is fixed update to `grunt-potomo v3.2.1` as it has update for `shelljs` npm package which resolves this issue in PowerShell :(

**Comment by shazahm1** [comment]
@shivapoudel 

Unfortunately still not fixed in powershell but maybe because of a different bug in shelljs. I'll post this to arturadib/shelljs#17 since this is more relevant to post there.

I wonder if it a path issue, notice the very first error in the screenshot. The path is being truncated at the very first space in the path name. I'll have to move the project to a path without a space and see what happens.

![2015-03-17_13-24-48](https://cloud.githubusercontent.com/assets/1185008/6693492/be1c4376-cca9-11e4-8b55-185ecbf34f53.png)
